# -*- coding: utf-8 -*-
"""analyze_gc_content.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OO-9CmFaxc5gGEbiAcrnYnTgXytoc1MM
"""

def analyze_gc_content(dna_sequences):
  g=dna_sequences.count("G")
  c=dna_sequences.count("C")
  total=len(dna_sequences)
  gc=((g+c)/total)*100
  print("DNA sequence:",dna_sequences)
  print("GC content is:",gc)

  if(gc>50):
    print("This DNA sequence is GC-rich.\n")
  else:
    print("This DNA sequence is AT-rich.\n")
sequences=["ATGCGTACGTTAG",
    "AATTGGCC",
    "GGGCCCATA",
    "TTAACCGG",
    "TAATACTAG",
    "CGCATCGTAGGGCC"]
for dna in sequences:
  analyze_gc_content(dna)